# yaml-language-server: $schema=https://schemastore.org/yamllint
extends: default
rules:
  anchors:
    forbid-duplicated-anchors: true
    forbid-unused-anchors: true
  braces:
    forbid: non-empty
    max-spaces-inside-empty: 0
  brackets:
    forbid: non-empty
    max-spaces-inside-empty: 0
  comments:
    min-spaces-from-content: 1
  document-end:
    present: false
  document-start:
    present: false
  empty-lines:
    max: 1
  empty-values: enable
  float-values:
    require-numeral-before-decimal: true
  indentation:
    spaces: 2
  key-duplicates:
    forbid-duplicated-merge-keys: true
  key-ordering: enable
  line-length: disable
  quoted-strings:
    allow-quoted-quotes: true
    quote-type: single
    required: only-when-needed
  truthy:
    check-keys: false
