# yaml-language-server: $schema=https://schemastore.org/github-action
author: qwerty吃小庄
branding:
  color: white
  icon: image
description: Convert between various image formats. (SVG to PNG) (PNG to JPEG) (JPEG to PNG) (SVG to PNG custom size)
inputs:
  repository:
    default: https://github.com/feraxhp/cim.git
    description: 'The repository of CIM.'
  revision:
    description: 'The branch, tag or SHA of CIM.'
name: Setup CIM
runs:
  steps:
    - env:
        REPOSITORY: ${{ inputs.repository }}
        REVISION: ${{ inputs.revision }}
      run: git clone -n --depth 1 --filter tree:0 ${{ inputs.revision && '--revision "$REVISION"' }} "$REPOSITORY" ${{ runner.temp }}/cim
      shell: bash
    - id: sha
      run: echo "sha=$(git rev-parse HEAD)" > $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ runner.temp }}/cim
    - id: cache
      uses: actions/cache@v4
      with:
        key: cim-${{ runner.arch }}-${{ runner.os }}-${{ steps.sha.outputs.sha }}
        path: ${{ runner.temp }}/cim
    - if: 'steps.cache.outputs.cache-hit == "false"'
      run: git checkout
      shell: bash
      working-directory: ${{ runner.temp }}/cim
    - if: 'steps.cache.outputs.cache-hit == "false"'
      run: cargo build --release
      shell: bash
      working-directory: ${{ runner.temp }}/cim
    - run: echo "${{ runner.temp }}/cim/target/release" >> $GITHUB_PATH
      shell: bash
  using: composite
