# yaml-language-server: $schema=https://schemastore.org/github-action
author: qwerty吃小庄
branding:
  color: white
  icon: image
description: Convert between various image formats. (SVG to PNG) (PNG to JPEG) (JPEG to PNG) (SVG to PNG custom size)
inputs:
  path:
    default: ${{ runner.temp }}/cim
    description: The path of CIM.
  repository:
    default: https://github.com/feraxhp/cim
    description: The repository of CIM.
  revision:
    description: The branch, tag or SHA of CIM.
name: Setup CIM
runs:
  steps:
    - env:
        CIM_HOME: ${{ inputs.path }}
        REPOSITORY: ${{ inputs.repository }}
        REVISION: ${{ inputs.revision }}
      run: git clone -n --depth 1 --filter tree:0 ${{ inputs.revision && '--revision "$REVISION"' }} "$REPOSITORY" "$CIM_HOME"
      shell: bash
    - id: sha
      run: echo "sha=$(git rev-parse HEAD)" > $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ inputs.path }}
    - id: cache
      uses: actions/cache@v5
      with:
        key: cim-${{ runner.arch }}-${{ runner.os }}-${{ steps.sha.outputs.sha }}
        path: |
          ${{ inputs.path }}/target/release/cim
          ${{ inputs.path }}/target/release/cim.exe
    - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: git checkout
      shell: bash
      working-directory: ${{ inputs.path }}
    - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: cargo build --release
      shell: bash
      working-directory: ${{ inputs.path }}
    - env:
        CIM_HOME: ${{ inputs.path }}
      run: echo "$CIM_HOME/target/release" > $GITHUB_PATH
      shell: bash
  using: composite
