# yaml-language-server: $schema=https://schemastore.org/github-workflow
jobs:
  check:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - if: ${{ runner.arch == 'x64' && runner.os == 'Linux' }}
        uses: pipeline-components/yamllint@d977118a71dcd79ac575885f22a2b318cc5fa128
      - uses: ./
      - run: cim -V
      - uses: ./
        with:
          path: ${{ runner.temp }}/cim-v0.1.0
          revision: v0.1.0-alpha
      - run: cim -V
    strategy:
      matrix:
        os:
          - macos-26
          - macos-26-intel
          - ubuntu-24.04-arm
          - ubuntu-24.04
          - windows-11-arm
          - windows-2025
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
permissions:
  contents: read
